site_name: 我的技术博客
theme:
  name: terminal
  palette: gruvbox_dark
  language: zh # 设置中文界面
  features:
    - navigation.tabs # 启用顶部标签页
    - content.code.copy # 启用代码块复制按钮

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/highlight.min.js
  - https://unpkg.com/highlightjs-cobol/dist/cobol.min.js
  - add_hljs_highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/styles/a11y-dark.min.css
